language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
env:
  global:
    - PUBLISH_BRANCH=master BUILD_BRANCH="builder" wheelhouse="$HOME/wheelhouse"
install:
  - pip install wheel
before_script:
  - git clone --quiet --depth=1 --branch=$PUBLISH_BRANCH https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG travis-wheels
script:
  - ./build_wheels.sh
  - travis_retry ./push_wheels.sh
matrix:
  allow_failures:
    - python: nightly